// frontend/src/app/dashboard/map/map.component.ts
import { Component, OnChanges, Input, SimpleChanges } from '@angular/core';
import { max, byID, calculateLightness } from './map.helpers';
import { Province, Cases, validHue } from '../types/data.types';

@Component({
  selector: 'app-map',
  templateUrl: './map.component.html',
  styleUrls: ['./map.component.scss'],
})
export class MapComponent implements OnChanges {
  @Input() provinces: Province[];
  @Input() casesInProvinces: Cases[];
  @Input() hue: validHue = 355;

  private maxCases = 0;

  getColorByID(id: string): string {
    if (!this.casesInProvinces) {
      return 'black';
    }

    const casesInProvince = this.casesInProvinces.find(byID(id))?.cases;
    const lightness = calculateLightness(casesInProvince, this.maxCases);
    return `hsla(${this.hue},100%,${lightness}%,1)`;
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes.casesInProvinces) {
      this.maxCases = this.casesInProvinces.reduce(
        max,
        this.casesInProvinces[0] ? this.casesInProvinces[0].cases : 0
      );
    }
  }
}

<svg
  xmlns="http://www.w3.org/2000/svg"
  mapsvg:geoViewBox="14.122232 54.834941 24.149724 49.002699"
  viewBox="0 0 612.75696 577.23169"
  class="svg-root"
  [attr.aria-labelledby]="titleID"
>
  <g role="list">
    <path
      role="listitem"
      *ngFor="let province of provinces"
      [attr.d]="province.borders"
      [id]="province.id"
      [attr.fill]="getColorByID(province.id)"
      stroke="black"
      [attr.aria-label]="getProvinceDescriptionByID(province.id)"
    ></path>
  </g>
</svg>

<app-tooltip
  [content]="tooltipContent"
  [postion]="tooltipPosition"
  [isVisible]="isTooltipVisible"
></app-tooltip>

// apps/react/src/app/dashboard/map/map.tsx
import React, { useState, useRef, useEffect, useReducer } from 'react';
import { Province, Cases } from '@covid-app/types';
import {
  calculateColor,
  getMaxCases,
  calcTooltipState,
} from '@covid-app/helpers';
import { fromEvent } from 'rxjs';
import { filter, debounceTime } from 'rxjs/operators';
import useTooltip from './useTooltip/useTooltip';

import './map.scss';

const hue = 355;
const tooltipTime = 1000;

export interface MapProps {
  titleID: string;
  provinces: Province[];
  cases: Cases[];
}

export const Map: React.FC<MapProps> = ({ cases, titleID, provinces }) => {
  const [maxCases, setMaxCases] = useState(0);
  const [Tooltip, setTooltipState] = useTooltip(['', { x: 0, y: 0 }, false]);

  const svgRootEl = useRef(null);
  const isMouseOver = useRef(false);

  useEffect(() => {
    setMaxCases(getMaxCases(cases));
  }, [cases]);

  useEffect(() => {
    const event = fromEvent<MouseEvent>(svgRootEl.current, 'mousemove')
      .pipe(
        debounceTime(tooltipTime),
        filter(() => isMouseOver.current)
      )
      .subscribe((e) => {
        setTooltipState(calcTooltipState(e, provinces, cases));
      });

    return () => event.unsubscribe();
  }, []);

  return (
    <div>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 612.75696 577.23169"
        className="svg-root"
        role="group"
        aria-labelledby={titleID}
        aria-describedby="map-description"
        ref={svgRootEl}
        onMouseOver={() => (isMouseOver.current = true)}
        onMouseOut={() => (isMouseOver.current = false)}
        onMouseMove={() => setTooltipState(['', { x: 0, y: 0 }, false])}
      >
        <desc id="map-description">
          COVID-19 cases in provinces on given date
        </desc>
        <g role="list">
          {provinces.map(({ borders, id, name }) => (
            <path
              key={id}
              role="listitem"
              d={borders}
              id={id}
              fill={calculateColor(hue, id, maxCases, cases)}
              stroke="black"
              aria-label="TODO"
            ></path>
          ))}
        </g>
      </svg>
      {Tooltip}
    </div>
  );
};

export default Map;
