// apps/covid/src/app/dashboard/map/map.component.ts
import {
  Component,
  OnChanges,
  Input,
  SimpleChanges,
  HostListener,
  EventEmitter,
  OnInit,
  OnDestroy,
} from '@angular/core';
import {
  calcTooltipState,
  getByID,
  calculateColor,
  getMaxCases,
  calcTooltipStateFromMouseEvent,
  calcTooltipStateFromFocusEvent,
  getProvinceDescription,
} from '@covid-app/helpers';
import { Province, Cases } from '@covid-app/types';
import { filter, debounceTime } from 'rxjs/operators';
import { Subscription } from 'rxjs';

@Component({
  selector: 'covid-app-map',
  templateUrl: './map.component.html',
  styleUrls: ['./map.component.scss'],
})
export class MapComponent implements OnChanges, OnInit, OnDestroy {
  @Input() provinces: Province[];
  @Input() casesInProvinces: Cases[];
  @Input() hue = 355;
  @Input() titleID: string;

  private maxCases = 0;

  public isTooltipVisible = false;
  public tooltipPosition = { x: 0, y: 0 };
  public tooltipContent = '';

  readonly tooltipTime = 1000;

  private mouseMove$ = new EventEmitter<MouseEvent>();
  private mouseMoveSubscription: Subscription;
  private isMouseOver = false;

  ngOnInit(): void {
    this.mouseMoveSubscription = this.mouseMove$
      .pipe(
        debounceTime(this.tooltipTime),
        filter(() => this.isMouseOver)
      )
      .subscribe((event) => this.handleTooltip(event));
  }

  ngOnDestroy(): void {
    this.mouseMoveSubscription.unsubscribe();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes.casesInProvinces) {
      this.maxCases = getMaxCases(this.casesInProvinces);
    }
  }

  @HostListener('mousemove', ['$event'])
  onMouseMove(event: MouseEvent): void {
    this.hideTooltip();
    this.mouseMove$.emit(event);
    event.stopPropagation();
  }

  getColorByID(id: string): string {
    if (!this.casesInProvinces) return 'black';

    return calculateColor(this.hue, id, this.maxCases, this.casesInProvinces);
  }

  handleTooltip(event: MouseEvent): void {
    [
      this.tooltipContent,
      this.tooltipPosition,
      this.isTooltipVisible,
    ] = calcTooltipStateFromMouseEvent(
      event,
      this.provinces,
      this.casesInProvinces
    );
  }

  getProvinceDescriptionByID(id: string): string {
    return getProvinceDescription(id, this.provinces, this.casesInProvinces);
  }

  updateMouseInfo(type: string) {
    this.isMouseOver = type === 'mouseover' ? true : false;
  }

  showTooltip(event: FocusEvent) {
    [
      this.tooltipContent,
      this.tooltipPosition,
      this.isTooltipVisible,
    ] = calcTooltipStateFromFocusEvent(
      event,
      this.provinces,
      this.casesInProvinces
    );
  }

  hideTooltip() {
    this.isTooltipVisible = false;
  }
}

<svg
  xmlns="http://www.w3.org/2000/svg"
  viewBox="0 0 612.75696 577.23169"
  class="svg-root"
  role="group"
  [attr.aria-labelledby]="titleID"
  aria-describedby="map-description"
  (mouseover)="updateMouseInfo($event.type)"
  (mouseout)="updateMouseInfo($event.type)"
>
  <desc id="map-description">
    COVID-19 cases in provinces on given date
  </desc>
  <g role="list">
    <path
      [attr.tabindex]="0"
      (focus)="showTooltip($event)"
      (blur)="hideTooltip()"
      role="listitem"
      *ngFor="let province of provinces"
      [attr.d]="province.borders"
      [id]="province.id"
      [attr.fill]="getColorByID(province.id)"
      stroke="black"
      [attr.aria-label]="getProvinceDescriptionByID(province.id)"
    ></path>
  </g>
</svg>

<covid-app-tooltip
  [content]="tooltipContent"
  [postion]="tooltipPosition"
  [isVisible]="isTooltipVisible"
></covid-app-tooltip>

// apps/react/src/app/dashboard/map/map.tsx
import React, { useState, useRef, useEffect, useReducer } from 'react';
import { Province, Cases } from '@covid-app/types';
import {
  calculateColor,
  getMaxCases,
  calcTooltipState,
} from '@covid-app/helpers';
import { fromEvent } from 'rxjs';
import { filter, debounceTime } from 'rxjs/operators';
import useTooltip from './useTooltip/useTooltip';

import './map.scss';

const hue = 355;
const tooltipTime = 1000;

export interface MapProps {
  titleID: string;
  provinces: Province[];
  cases: Cases[];
}

export const Map: React.FC<MapProps> = ({ cases, titleID, provinces }) => {
  const [maxCases, setMaxCases] = useState(0);
  const [Tooltip, setTooltipState] = useTooltip(['', { x: 0, y: 0 }, false]);

  const svgRootEl = useRef(null);
  const isMouseOver = useRef(false);

  useEffect(() => {
    setMaxCases(getMaxCases(cases));
  }, [cases]);

  useEffect(() => {
    const event = fromEvent<MouseEvent>(svgRootEl.current, 'mousemove')
      .pipe(
        debounceTime(tooltipTime),
        filter(() => isMouseOver.current)
      )
      .subscribe((e) => {
        setTooltipState(calcTooltipState(e, provinces, cases));
      });

    return () => event.unsubscribe();
  }, []);

  return (
    <div>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 612.75696 577.23169"
        className="svg-root"
        role="group"
        aria-labelledby={titleID}
        aria-describedby="map-description"
        ref={svgRootEl}
        onMouseOver={() => (isMouseOver.current = true)}
        onMouseOut={() => (isMouseOver.current = false)}
        onMouseMove={() => setTooltipState(['', { x: 0, y: 0 }, false])}
      >
        <desc id="map-description">
          COVID-19 cases in provinces on given date
        </desc>
        <g role="list">
          {provinces.map(({ borders, id, name }) => (
            <path
              key={id}
              role="listitem"
              d={borders}
              id={id}
              fill={calculateColor(hue, id, maxCases, cases)}
              stroke="black"
              aria-label="TODO"
            ></path>
          ))}
        </g>
      </svg>
      {Tooltip}
    </div>
  );
};

export default Map;
